Repository zoeyourlife/Core-JavaScript, pull requests merged in 2023-08, with the labels that each got.

#11 어준혁 2장 실행컨텍스트
  2_실행컨텍스트/어준혁.md
Labels: 2장

#13 김특희 2장 실행컨텍스트
  2_실행컨텍스트/김특희.md
Labels: 2장

#15 어준혁 3장 this
  3_this/어준혁.md
Labels: 3장

#14 이영욱 3장 정리
  3_this/이영욱.md
Labels: 3장

#16 남현준 3장 this
  3_this/남현준.md
Labels: 3장

#17 김특희 3장 this
  3_this/김특희.md
Labels: 3장

#18 최재훈 3장
  3_this/최재훈.md
Labels: 3장

#21 4장 콜백함수
  4_콜백함수/남현준.md
Labels: 4장

#23 김특희 4장: 콜백함수
  4_콜백함수/김특희.md
Labels: 4장

#20 어준혁 4장 콜백함수
  4_콜백함수/어준혁.md
Labels: 4장

#19 이영욱 4장 정리
  4_콜백함수/이영욱.md
Labels: 4장

#22 최재훈 4장
  4_콜백함수/최재훈.md
Labels: 4장

#26 남현준 5장
  5_클로저/남현준.md
Labels: 5장

#25 최재훈 5장
  5_클로저/최재훈.md
Labels: 5장

#27 김특희 5장 정리
  5_클로저/김특희.md
Labels: 5장

#24 이영욱 5장 정리
  5_클로저/이영욱.md
Labels: 5장
